# Ameba configuration for ansi library
Version: "1.7.0-dev"

Excluded:
  - temp/**/*
  - lib/**/*
  - vendor/**/*
  - spec/**/*
  - crystal-performance-workspace/**/*


Lint/Formatting:
  Excluded:
    - spec/**/*.cr
    - temp/**/*.cr


# add paths that need to be excluded so we track in one place
# Metrics/CyclomaticComplexity:
#   Excluded:
#     -
